lr: 0.003
num_epoch: 100
weight_decay: 0
runs: 2
embedding_dim: 64
patience: 400
g_batch_size: 500
subgraph_size: 4
readout: 'avg'
auc_test_rounds: 50
negsamp_ratio: 1
alpha: 1.0
beta: 0.6